### ISSUE TITLE
Error with default installation

### ISSUE THREAD

**Issue by zenyuk** [hanishkvc/go-apropos#1]
When trying to search for anything, e.g.:
```
$ goapropos os
```
Getting this error:
```
GOAPRO:ERRR:Cache: Version:stat /usr/share/go-dummy/: no such file or directory
```

Version: ce265783e160b34d373ee47ec3b32f3ef9375a4e

Environment:
```
$ go version
go version go1.18 darwin/arm64

$ which go
/opt/homebrew/bin/go
```

**Comment by hanishkvc** [comment]
Previously I had predefined the go src paths wrt debian and fedora/RH based distros, as that is what I was experimenting on, that is the reason why it failed on MacOS for you.

With the latest release, now I first look at the GOROOT path before falling back to the predefined paths, with this it should potentially work on the MacOS homebrew setup you seem to be using. Do cross check once, chances are it should work.

NOTE: Even with the old release, you could have passed the --basepath argument with the path to the go package's src directory and it would have worked. However you would have had to pass this argument each time you used goapropos. With the new release if it picks up the go src automatically (which potentially it should), this wont be needed. Also I am thinking of adding a config file, which would avoid the need for passing such or any other arguments on the command line each time.

**Comment by hanishkvc** [comment]
Also on a slightly different note, ie just in case if required, goapropos works slightly different from go doc.

With go doc, running
`
$ go doc os
`
would give you all the exported symbols (types, consts, vars, functions) and associated comment wrt the os package

However with goapropos, running
`
$ goapropos os
`
would give all the symbols which contain os in their name, from across all the packages.

While
`
$ goapropos --findpkg "packagename$" --find ""
`
would give all symbols from the package named packagename, as well as the files associated with the package.

If the symbols have any associated comments wrt them, then a short snippet of the same is also shown.
